#+TITLE: Minha configuração do Emacs
#+AUTHOR: Tukain
#+SETUPFILE: ./export.org

O objetivo dessa configuração é ser um equivalente à minha
configuração do [[https://github.com/ventriloquo/nvim][Neovim]], desde teclas de atalho a pacotes similares,
com a diferença sendo que aqui eu tento "documentar" /ao máximo/ +tudo+
o que está acontecendo (para que pelo menos eu consiga entender o que
*CACETARALHOS* está acontecendo aqui).

/OBS: Essa configuração é também pronta para exportação HTML./

* Bons padrões

O Emacs é um ótimo programa com padrões horrorosos,
então vamos dar um jeito nisso.

#+begin_src emacs-lisp
(setq backup-directory-alist '(("." . "~/.config/emacs/backups"))
      inhibit-startup-message t
      inhibit-startup-echo-area-message t
      tooltip-use-echo-area t
      custom-file "~/.config/emacs/custom.el")
(load custom-file)
(setq-default minor-mode-alist nil
	      fill-column 120)

(require 'ido)
(ido-mode t)
(ido-everywhere t)
(tooltip-mode -1)
(delete-selection-mode 1)

;; Não mostrar caixas de diálogos usando UI.
(setq use-dialog-box nil)

;; Refrescar todos os buffers quando os arquivos presentes
;; neles forem alterados externamente
(global-auto-revert-mode 1)
(setq global-auto-revert-non-file-buffers t)

;; Só mostra alguma mensagem de erro caso ela seja considerada
;; uma "emergência" (Algo que pode impedir o funcionamento do Emacs).
;;
;; Todo o resto que seja considerado abaixo desse nível é mostrado
;; apenas no buffer "*Warning*"
(setq warning-minimum-level
      :emergency)
#+end_src

* Org-mode

Coisinhas que melhoram a experiência de usar o Org-mode.

#+begin_src emacs-lisp
(require 'org-tempo)
(setq org-support-shift-select t
      org-edit-src-content-indentation 0)
(setq-default org-startup-indented t
              org-pretty-entities t
              org-use-sub-superscripts "{}"
              org-hide-emphasis-markers t
              org-startup-with-inline-images t
              org-image-actual-width '(300))
#+end_src

* Aparência

Configurações relacionadas a parte mais estética do Emacs,
apesar de ter algumas coisas que ajudam também na usabilidade.

#+begin_src emacs-lisp
(scroll-bar-mode 0)
(tool-bar-mode 0)
(menu-bar-mode 0)
(add-to-list 'default-frame-alist '(font . "jetbrainsmono-10"))
(global-prettify-symbols-mode)
(global-hl-line-mode t)
(icomplete-mode 1)
(setq-default whitespace-style
    '(face trailing space-mark tab-mark))
(set-frame-parameter nil 'alpha-background 100)
(add-to-list 'default-frame-alist '(alpha-background . 100))
;;(display-time-mode 1)
;;(display-battery-mode 1)
;;(global-whitespace-mode)
;;(global-display-fill-column-indicator-mode t)
#+end_src

* Pacotes

Toda a magia dessa configuração vem desses pacotes.

** MELPA e Use-package

Aqui fica todo o processo de configuração do repositório [[https://melpa.org][MELPA]]
e do /macro/ =use-package=.

#+begin_src emacs-lisp
;; Configurando o MELPA
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

;; Configurando o use-package
(require 'use-package)
(setq use-package-always-ensure t)
#+end_src

** Instalação de pacotes

Aqui fica todo o processo de instalação dos pacotes que são utilizados nessa configuração.

#+begin_src emacs-lisp
;; TODO: Remover essa linha quando o Emacs 30 virar mainstream.
(use-package which-key
  :config (which-key-mode))

;; Code completion
(use-package company
  :config
  (global-company-mode)
  (setq company-idle-delay 0))

;; Basicamente, pega código-fonte e exporta em HTML.
(use-package htmlize)

;; Um dos melhores clientes Git existentes (junto do Lazygit!)
(use-package magit)

;; Um servidor http simples :P
(use-package simple-httpd)

;; Painel lateral para navegação de arquivos.
(use-package neotree)

;; Mode-line
(use-package doom-modeline
  :config (doom-modeline-mode))

;; EVIL MODE!
(use-package evil
  :config
  ;; Deixando a "leader key" ser "Espaço"
  (evil-set-leader 'normal (kbd "SPC"))
  (evil-mode))

;; Teclas de atalho extremamente úteis para o Evil-mode
(use-package evil-collection
  :config
  (evil-collection-init))

;; Ícones 
(use-package all-the-icons)
(use-package all-the-icons-ibuffer)
(use-package all-the-icons-dired)
(use-package all-the-icons-nerd-fonts)

;; TODO: Documentar essa seção.
(use-package visual-fill-column)

;; Destacar palavras como TODO ou FIXME
(use-package hl-todo
  :hook (prog-mode . hl-todo-mode)
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces
        `(("TODO"       warning bold)
          ("FIXME"      error bold)
          ("HACK"       font-lock-constant-face bold)
          ("REVIEW"     font-lock-keyword-face bold)
          ("NOTE"       success bold)
          ("DEPRECATED" font-lock-doc-face bold))))

;; A tela inicial do Emacs
(use-package dashboard
  :config
  (setq dashboard-banner-logo-title nil)
  (setq dashboard-startup-banner "~/.config/emacs/logo.png")
  (setq dashboard-center-content t)
  (setq dashboard-vertically-center-content t)
  (dashboard-open))
#+end_src

** Hare-mode
Syntax-highlighting para a linguagem [[https://harelang.org][Hare]].

Esse pacote não está disponível ainda em nenhum package registry
conhecido, como o [[https://melpa.org/][MELPA]], então eu baixei diretamente do
[[https://git.sr.ht/~laumann/hare-mode][repositório original]] e carrego ela junto do meu setup.

#+begin_src emacs-lisp
(load-file "~/.config/emacs/etc/hare-mode.el")
#+end_src

** Temas

Convenhamos, o tema padrão do Emacs é capaz de assustar até um cadáver de tão feio.

Por isso, aqui vão alguns temas para deixar esse carinha uma belezura!

#+begin_src emacs-lisp
;; Ajustando alguns detalhes do tema "Modus", um dos temas pré
;; instalados no Emacs (um muito bonito inclusive).
;;(setq modus-themes-mode-line '(borderless accented 4 1.0))
;;(setq modus-themes-region '(bg-only))
;;(setq modus-themes-bold-constructs t
;;      modus-themes-italic-constructs t
;;      modus-themes-paren-match '(intense))
;;(setq modus-themes-headings
;;      '((1 . (rainbow background 1.5))
;;	(2 . (rainbow background 1.4))
;;	(3 . (rainbow background 1.3))
;;	(4 . (rainbow background 1.2))
;;	(t . (rainbow background 1.1))))
;;(setq modus-themes-org-blocks 'tinted-background)
;;(load-theme 'modus-vivendi t)

;; Temas externos
(use-package kanagawa-themes)
(use-package gruber-darker-theme)
(use-package doom-themes)

(load-theme 'kanagawa-wave t)
#+end_src

* Hooks
** prog-mode-hook
Esse hook serve basicamente para ativar a barra lateral
com os números das linhas, mas somente quando um arquivo
de código-fonte estiver sendo editado.

Assim, se você abrir um arquivo =.org= você não vai ter
uma linha de números ativada.

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook
	  (lambda ()
	    (display-line-numbers-mode t)))
#+end_src

** TODO visual-fill-column
#+begin_src emacs-lisp
(add-hook 'org-mode-hook
	  (lambda ()
	    (visual-fill-column-mode)
        (visual-line-fill-column-mode)
	    (visual-fill-column-toggle-center-text)))
#+end_src

** all-the-icons-ibuffer

Coloca ícones no iBuffer \o/

#+begin_src emacs-lisp
(add-hook 'ibuffer-mode-hook
	  (lambda ()
	    (all-the-icons-ibuffer-mode)))
#+end_src
* Teclas de atalho

É claro que eu não iria deixar de adicionar *MAIS* teclas de
atalho para um programa que, entre outras coisas, é conhecido
por ter uma cacetada de teclas de atalho.

** Window/buffer controls
#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>s") 'save-buffer)
(evil-define-key 'normal 'global (kbd "<leader>c") 'kill-current-buffer)
(evil-define-key 'normal 'global (kbd "<leader><tab>")     'next-buffer)
(evil-define-key 'normal 'global (kbd "<leader><backtab>") 'previous-buffer)
(evil-define-key 'normal 'global (kbd "<leader>v") 'split-window-horizontally)
(evil-define-key 'normal 'global (kbd "<leader>V") 'split-window-vertically)
(evil-define-key 'normal 'global (kbd "<leader>q") 'delete-window)
(evil-define-key 'normal 'global (kbd "<leader>h") 'windmove-left)
(evil-define-key 'normal 'global (kbd "<leader>j") 'windmove-down)
(evil-define-key 'normal 'global (kbd "<leader>k") 'windmove-up)
(evil-define-key 'normal 'global (kbd "<leader>l") 'windmove-right)
#+end_src

** Find-file-at-point

Basicamente, você deixa o cursor encima de algum /file path/ e esse
comando vai tentar abrir esse arquivo. 

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>.") 'ffap)
#+end_src

** Eshell

O shell/terminal embutido do Emacs, feito utilizando Elisp e que
também vem com algumas das ferramentas do projeto [[https://www.gnu.org/][GNU]] re-escritas
com Elisp.

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>e") 'eshell)
#+end_src

** Whitespace-mode

Mostra (utilizando alguns caracteres) os espaços em branco.

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>W") 'global-whitespace-mode)
#+end_src

** Número de linhas

Isso aqui serve basicamente para mostrar ou esconder a linha de números.

Por padrão, a minha configuração esconde a linha de números em arquivos que não
sejam considerados /source-code/. Sendo assim, se você criar um arquivo =.org=, =.md=, =.txt= ou
algo do gênero, você não verá a linha de números.

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>N") 'global-display-line-numbers-mode)
#+end_src

** Indicador de "limite" caracteres

Tente ao máximo se limitar a usar 80 caracteres de largura em
*TUDO*.

/Ironicamente, essa linha de código ultrapassa esse limite :P/

#+begin_quote
Esse comando depende de como a variável "fill-column" está configurada.

Por exemplo, se ela estiver configurada para ser 80, então uma barra vai aparecer na posição 80.
#+end_quote

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>F") 'global-display-fill-column-indicator-mode)
#+end_src

** IBuffer

Lista "interativa" de buffers.

/É, eu também acho esse nome paia./

#+begin_src emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
(evil-define-key 'normal 'global (kbd "<leader>b") 'ibuffer)
#+end_src

** Compile

Essa tecla de atalho tem um certo "contexto" do porquê ser =<leader>m= no
lugar de =<leader>c= ("c" de compile). O contexto é bem simples:
Na minha configuração do Neovim eu tenho a mesma tecla de atalho, e ela
executa o =make=, o que eu usava para agilizar o processo de compilar as
[[https://github.com/ventriloquo/hare_raylib][minhas bindings da raylib]].

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>m") 'compile)
(evil-define-key 'normal 'global (kbd "<leader>M") 'recompile)
#+end_src

** Modus-themes-toggle

Uma coisa muito legal que o tema Modus oferece é uma forma de
alterar entre a versão do tema claro e o tema escuro facilmente.

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>Tm") 'magit)
#+end_src

** Dired

É claro que eu vou adicionar uma tecla de atalho para abrir o Dired.

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>d") 'dired)
#+end_src

** Magit

Bom, isso aqui abre o Magit. Não tem muito o que explicar aqui.

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>g") 'magit)
#+end_src

** Neotree

Painel lateral com uma árvore de arquivos (que nem o "nvim-tree" presente
na minha configuração do Neovim).

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>n") 'neotree-toggle)
#+end_src

** Hl-todo

Destaca e lista todas as ocorrências das palavras TODO, FIXME e relacionadas.

#+begin_src elisp
(evil-define-key 'normal 'global (kbd "<leader>t") 'hl-todo-occur)
#+end_src

** Bookmark-jump

Seletor de Bookmarks

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>B") 'bookmark-jump)
#+end_src
** Download-file

Um /wrapper/ para a função =(url-copy-file)=.

Com um simples =Espaço= + =d= você consegue fazer o download de qualquer arquivo na internet!

#+begin_src emacs-lisp
(defun download-file (url path)
  "Um wrapper para a função (url-copy-file)"
  (interactive
   (list
    (setq url (read-string "URL: " "https://"))
    (setq path (read-string "PATH: " "~/"))))
  (url-copy-file (format "%s" url) (format "%s" path) t))

(evil-define-key 'normal 'global (kbd "<leader>D") 'download-file)
#+end_src
** Reiniciar o Emacs

/Eu preciso mesmo te dizer o que isso faz? ._./

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>r") 'restart-emacs)
#+end_src

** Org-mode

O org-mode é definitivamente um dos trunfos do Emacs e eu uso isso com uma certa frequência.
Por conta disso, eu vou deixar algumas teclas de atalho aqui que facilitam a minha vida.

*** open-at-point

Abre o arquivo presente em um link que está abaixo do =point= (cursor).

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>SPC o") 'org-open-at-point)
#+end_src

*** insert-link

Inserir um link.

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>SPC l") 'org-insert-link)
#+end_src

*** export-dispatch

Menu de exportação de documentos =.org=.

#+begin_quote
Experimente!

É só apertar =Espaço= + =Espaço= + =e= + =h= + =h= (usando as /keybinds/ do Evil-mode) ou
=Ctrl= + =c= + =Ctrl= + =e= (usando as /keybinds/ do Emacs) e você terá como resultado um arquivo
HTML desta configuração!
#+end_quote

#+begin_src emacs-lisp
(evil-define-key 'normal 'global (kbd "<leader>SPC e") 'org-export-dispatch)
#+end_src
